// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockManager.Infrastructure.Persistence;

#nullable disable

namespace StockManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StockManagementDbContext))]
    [Migration("20260331104013_ErpPhase6_CreateArticleEtatDetail")]
    partial class ErpPhase6_CreateArticleEtatDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Catalogue.ArticleChampValeur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("ChampSpecifiqueId")
                        .HasColumnType("int");

                    b.Property<string>("Valeur")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChampSpecifiqueId");

                    b.HasIndex("ArticleId", "ChampSpecifiqueId")
                        .IsUnique();

                    b.ToTable("ARTICLE_CHAMP_VALEUR", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Catalogue.ArticleEtatDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int?>("GarantieOfferte")
                        .HasColumnType("int");

                    b.Property<string>("GradeVisuel")
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("PannesObservees")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevisionsEffectuees")
                        .HasColumnType("TEXT");

                    b.Property<string>("TestsFonctionnels")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId")
                        .IsUnique();

                    b.ToTable("ARTICLE_ETAT_DETAIL", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Catalogue.ChampSpecifique", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("NomChamp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Obligatoire")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Ordre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TypeDonnee")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("TEXTE");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("CHAMP_SPECIFIQUE", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Catalogue.Famille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Familles", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("FamilleId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TypeGestionStock")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("QUANTITE");

                    b.HasKey("Id");

                    b.HasIndex("FamilleId");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.BonCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCommande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("NumeroBC")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("EN_ATTENTE");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("NumeroBC")
                        .IsUnique();

                    b.ToTable("BON_COMMANDE", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.BonLivraison", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AdresseLivraison")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BonCommandeId")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateLivraison")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("NumeroBL")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("NumeroSuivi")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("BROUILLON");

                    b.Property<string>("Transporteur")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BonCommandeId");

                    b.HasIndex("ClientId");

                    b.HasIndex("NumeroBL")
                        .IsUnique();

                    b.ToTable("BON_LIVRAISON", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Societe")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("CLIENT", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.Lead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CommercialId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSoumission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("DateTraitement")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroDevis")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("SourceAcquisition")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("DIRECT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("NOUVEAU");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CommercialId");

                    b.HasIndex("NumeroDevis")
                        .IsUnique();

                    b.ToTable("LEAD", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.LigneBC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("BonCommandeId")
                        .HasColumnType("int");

                    b.Property<int>("QuantiteCommandee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("BonCommandeId");

                    b.ToTable("LIGNE_BC", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.LigneBL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("BonLivraisonId")
                        .HasColumnType("int");

                    b.Property<int?>("LotId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSerie")
                        .HasColumnType("longtext");

                    b.Property<int>("QuantiteLivree")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("BonLivraisonId");

                    b.ToTable("LIGNE_BL", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.LigneLead", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<int>("QuantiteDemandee")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("LeadId");

                    b.ToTable("LIGNE_LEAD", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.ContactRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ContactRequests");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ArticleSimilaireIds")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DatasheetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("DisponibiliteSite")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("EN_STOCK");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MinThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("PrixAchat")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrixVente")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("VisibleSite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.AlerteStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepotId")
                        .HasColumnType("int");

                    b.Property<bool>("EstResolue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("NiveauAlerte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("QuantiteAuDeclenchement")
                        .HasColumnType("int");

                    b.Property<int>("SeuilUtilise")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("ArticleId", "DepotId")
                        .HasDatabaseName("IX_AlertesStock_ArticleId_DepotId");

                    b.ToTable("AlertesStock", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.Depot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Depots", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Certificat")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DateEntree")
                        .HasColumnType("DATE");

                    b.Property<int>("DepotId")
                        .HasColumnType("int");

                    b.Property<string>("Fournisseur")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Garantie")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NumeroLot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("DepotId");

                    b.HasIndex("NumeroLot", "ArticleId", "DepotId")
                        .IsUnique();

                    b.ToTable("LOT", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.NumeroSerie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEntree")
                        .HasColumnType("DATE");

                    b.Property<int>("DepotId")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSerieLabel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("DepotId");

                    b.HasIndex("NumeroSerieLabel")
                        .IsUnique();

                    b.ToTable("NUMERO_SERIE", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.StockQuantite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("DepotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SeuilMinimum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("ArticleId", "DepotId")
                        .IsUnique()
                        .HasDatabaseName("IX_StockQuantites_ArticleId_DepotId");

                    b.ToTable("StockQuantites", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int?>("DepotDestinationId")
                        .HasColumnType("int");

                    b.Property<int?>("DepotSourceId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int?>("LotId")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroSerieId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeMouvement")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("ENTREE");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepotDestinationId");

                    b.HasIndex("DepotSourceId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("LotId");

                    b.HasIndex("NumeroSerieId");

                    b.HasIndex("UserId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Catalogue.ArticleChampValeur", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Article")
                        .WithMany("ChampsSpecifiques")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.Catalogue.ChampSpecifique", "ChampSpecifique")
                        .WithMany("ArticleValues")
                        .HasForeignKey("ChampSpecifiqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("ChampSpecifique");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Catalogue.ArticleEtatDetail", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Article")
                        .WithOne("EtatDetail")
                        .HasForeignKey("StockManager.Core.Domain.Entities.Catalogue.ArticleEtatDetail", "ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Catalogue.ChampSpecifique", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Category", "Categorie")
                        .WithMany("ChampsSpecifiques")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Category", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Catalogue.Famille", "Famille")
                        .WithMany("Categories")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.BonCommande", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Commercial.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.BonLivraison", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Commercial.BonCommande", "BonCommande")
                        .WithMany("BonsLivraison")
                        .HasForeignKey("BonCommandeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StockManager.Core.Domain.Entities.Commercial.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BonCommande");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.Lead", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Commercial.Client", "Client")
                        .WithMany("Leads")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.User", "Commercial")
                        .WithMany()
                        .HasForeignKey("CommercialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Commercial");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.LigneBC", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.Commercial.BonCommande", "BonCommande")
                        .WithMany("Lignes")
                        .HasForeignKey("BonCommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("BonCommande");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.LigneBL", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.Commercial.BonLivraison", "BonLivraison")
                        .WithMany("Lignes")
                        .HasForeignKey("BonLivraisonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("BonLivraison");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.LigneLead", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.Commercial.Lead", "Lead")
                        .WithMany("Lignes")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.ContactRequest", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Equipment")
                        .WithMany("ContactRequests")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Category", "Category")
                        .WithMany("Equipments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Photo", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Equipment")
                        .WithMany("Photos")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.AlerteStock", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Article")
                        .WithMany("AlertesStock")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.Stock.Depot", "Depot")
                        .WithMany("AlertesStock")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.Lot", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Article")
                        .WithMany("Lots")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.Stock.Depot", "Depot")
                        .WithMany("Lots")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.NumeroSerie", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Article")
                        .WithMany("NumerosSerie")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.Stock.Depot", "Depot")
                        .WithMany("NumerosSerie")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.StockQuantite", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Article")
                        .WithMany("StockQuantites")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.Stock.Depot", "Depot")
                        .WithMany("StockQuantites")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Stock.Depot", "DepotDestination")
                        .WithMany("MouvementsDestination")
                        .HasForeignKey("DepotDestinationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockManager.Core.Domain.Entities.Stock.Depot", "DepotSource")
                        .WithMany("MouvementsSource")
                        .HasForeignKey("DepotSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Equipment")
                        .WithMany("StockMovements")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.Stock.Lot", "Lot")
                        .WithMany()
                        .HasForeignKey("LotId");

                    b.HasOne("StockManager.Core.Domain.Entities.Stock.NumeroSerie", "NumeroSerie")
                        .WithMany()
                        .HasForeignKey("NumeroSerieId");

                    b.HasOne("StockManager.Core.Domain.Entities.User", "User")
                        .WithMany("PerformedMovements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepotDestination");

                    b.Navigation("DepotSource");

                    b.Navigation("Equipment");

                    b.Navigation("Lot");

                    b.Navigation("NumeroSerie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Catalogue.ChampSpecifique", b =>
                {
                    b.Navigation("ArticleValues");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Catalogue.Famille", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Category", b =>
                {
                    b.Navigation("ChampsSpecifiques");

                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.BonCommande", b =>
                {
                    b.Navigation("BonsLivraison");

                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.BonLivraison", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.Client", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Commercial.Lead", b =>
                {
                    b.Navigation("Lignes");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("AlertesStock");

                    b.Navigation("ChampsSpecifiques");

                    b.Navigation("ContactRequests");

                    b.Navigation("EtatDetail");

                    b.Navigation("Lots");

                    b.Navigation("NumerosSerie");

                    b.Navigation("Photos");

                    b.Navigation("StockMovements");

                    b.Navigation("StockQuantites");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.Depot", b =>
                {
                    b.Navigation("AlertesStock");

                    b.Navigation("Lots");

                    b.Navigation("MouvementsDestination");

                    b.Navigation("MouvementsSource");

                    b.Navigation("NumerosSerie");

                    b.Navigation("StockQuantites");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("PerformedMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
