// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockManager.Infrastructure.Persistence;

#nullable disable

namespace StockManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(StockManagementDbContext))]
    [Migration("20260311152212_ErpPhase1_CreateCoreStockTables")]
    partial class ErpPhase1_CreateCoreStockTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Catalogue.Famille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Familles", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("FamilleId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TypeGestionStock")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("QUANTITE");

                    b.HasKey("Id");

                    b.HasIndex("FamilleId");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.ContactRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("ContactRequests");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ArticleSimilaireIds")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("DatasheetUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("DisponibiliteSite")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("EN_STOCK");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MinThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal?>("PrixAchat")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrixVente")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("VisibleSite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.ToTable("Equipments");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.AlerteStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("DateResolution")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepotId")
                        .HasColumnType("int");

                    b.Property<bool>("EstResolue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("NiveauAlerte")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("QuantiteAuDeclenchement")
                        .HasColumnType("int");

                    b.Property<int>("SeuilUtilise")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("ArticleId", "DepotId")
                        .HasDatabaseName("IX_AlertesStock_ArticleId_DepotId");

                    b.ToTable("AlertesStock", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.Depot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Adresse")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Depots", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.StockQuantite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("DepotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Quantite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SeuilMinimum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DepotId");

                    b.HasIndex("ArticleId", "DepotId")
                        .IsUnique()
                        .HasDatabaseName("IX_StockQuantites_ArticleId_DepotId");

                    b.ToTable("StockQuantites", (string)null);
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int?>("DepotDestinationId")
                        .HasColumnType("int");

                    b.Property<int?>("DepotSourceId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TypeMouvement")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("ENTREE");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepotDestinationId");

                    b.HasIndex("DepotSourceId");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("UserId");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Category", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Catalogue.Famille", "Famille")
                        .WithMany("Categories")
                        .HasForeignKey("FamilleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Famille");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.ContactRequest", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Equipment")
                        .WithMany("ContactRequests")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Category", "Category")
                        .WithMany("Equipments")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Photo", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Equipment")
                        .WithMany("Photos")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.AlerteStock", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Article")
                        .WithMany("AlertesStock")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.Stock.Depot", "Depot")
                        .WithMany("AlertesStock")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.StockQuantite", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Article")
                        .WithMany("StockQuantites")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.Stock.Depot", "Depot")
                        .WithMany("StockQuantites")
                        .HasForeignKey("DepotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Depot");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("StockManager.Core.Domain.Entities.Stock.Depot", "DepotDestination")
                        .WithMany("MouvementsDestination")
                        .HasForeignKey("DepotDestinationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockManager.Core.Domain.Entities.Stock.Depot", "DepotSource")
                        .WithMany("MouvementsSource")
                        .HasForeignKey("DepotSourceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("StockManager.Core.Domain.Entities.Equipment", "Equipment")
                        .WithMany("StockMovements")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StockManager.Core.Domain.Entities.User", "User")
                        .WithMany("PerformedMovements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepotDestination");

                    b.Navigation("DepotSource");

                    b.Navigation("Equipment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Catalogue.Famille", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Category", b =>
                {
                    b.Navigation("Equipments");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("AlertesStock");

                    b.Navigation("ContactRequests");

                    b.Navigation("Photos");

                    b.Navigation("StockMovements");

                    b.Navigation("StockQuantites");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.Stock.Depot", b =>
                {
                    b.Navigation("AlertesStock");

                    b.Navigation("MouvementsDestination");

                    b.Navigation("MouvementsSource");

                    b.Navigation("StockQuantites");
                });

            modelBuilder.Entity("StockManager.Core.Domain.Entities.User", b =>
                {
                    b.Navigation("PerformedMovements");
                });
#pragma warning restore 612, 618
        }
    }
}
