version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: capled-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: capled_stock
    ports:
      - "3306:3306"
    volumes:
      - capledproject_mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: capled-api
    depends_on:
      - database
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=database;Database=capled_stock;Uid=root;Pwd=root;
      - Logging__LogLevel__Default=Information

volumes:
  capledproject_mysql_data:
    external: true
